### PR TITLE
SCIPsolverConcurrent implementation from issue #229

### PR DESCRIPTION
**Pull request by TNonet**
Most of this code was thanks to @fserra from issue #229.

Hopefully, this will help support Concurrent pySCIPOpt

### CODE REVIEW

**Comment by mattmilten** [comment]
Another fortunate side effect of your contribution was that we realized that our CI actions did not run on PRs. So, this is also fixed now. You may have seen from the other PR #537 that concurrent optimization is only possible when compiling SCIP with a TPI (task processing interface) - this is not included in the default installer package.

**Comment by TNonet** [comment]
Thanks for your help fixing that PR. 

Is there any guide on how to compile SCIP with a TPI? I have attempted to compile SCIP (and then install pySCIPOpt from local source with the compile flag). However, I haven't seen any documentation on the TPI aspect.

A second, potentially, more relevant question is: Is it feasible to create an extra with pySCIPOpt that includes a TPI? For example (using PIP instead of conda to more clearly show the [extra] aspect).
```python
pip install pySCIPOpt[TPI]
```

I would be happy to help develop this, but I will need some guidance.

**Comment by mattmilten** [comment]
@CGraczyk can you assist here, please?

**Comment by CGraczyk** [comment]
Regarding the installation of SCIP with TPI, there is a compile option (see bottom of the table [here](https://www.scipopt.org/doc/html/md_INSTALL.php) whereby tny stands for TinyCThread and omp for OpenMP.
(See also [this issue](http://listserv.zib.de/pipermail/scip/2018-April/003342.html))

If you have more trouble with SCIP with TPI feel free to ask in the SCIP mailing list (have a look at [this](https://scipopt.org/index.php#contact)).

Regarding the developement of an extra i am not sure, what would be the goal here when using this?

**Comment by TNonet** [comment]
@CGraczyk Thank you for sharing those new resources. I will make sure I look into them.

The purpose of developing an extra, in my opinion, would be to take advantage of the concurrent and parallel solving capability of SCIP (https://www.scipopt.org/doc-5.0.1/html/CONCSCIP.php). However, I don't know if an extra is the appropriate method for this.

Specifically, I am looking into seeing if using the parallel/{max/min}nthreads parameter will help my MIP problem solve faster. I believe having the parallel and concurrent options available through an extra could be a way to make sure the current version of PySCIPOpt remains stable while still allowing for more "experimental" options for those interested.

Happy to discuss this further and figure out what (if any) way is appropriate.

**Comment by jirkacigler** [comment]
Hello, I am encountering problem when calling model.solveConcurrent() leading to segmentation fault.  I was trying to analyse where the problem is, but no success. 
I use clean ubuntu 20.04 LTS, scip sources 7.0.3, building SCIP with arguments
cmake .. -DSYM=bliss -DWORHP=off -DZIMPL=off -DTPI=tny -DPARASCIP=on -DIPOPT=off -DPAPILO=off 
Do you have any advise, how to build SCIP so that I can use solveConcurrent()? thank you

**Pull request merged**
