### PR TITLE
Correct output redirection

### LINKED ISSUE #243: "write" methods don't work after `redirectOutput()`
After calling `redirectOutput()`, e.g. `writeProblem()` does not produce a file but prints the problem description to the outstream.

Apparently, we redirect *everything* to the new messagehandler.

### PR DESCRIPTION
**Pull request by DominikKamp**
This resolves #243 by restricting method `redirectOutput()` to the streams `stdout` and `stderr`.

### CODE REVIEW

**Comment by Joao-Dionisio** [comment]
Hey hey, @DominikKamp, glad to see you here :smile: 

We had some problems with printing and people having weird locales [#830], [#843]. Do you think we might need to be concerned with this here as well?

Also, can you please add some tests?

**Comment by Joao-Dionisio** [comment]
Yeah, the output itself should be hard to test, but just that it's being printed to the correct place. We have a bunch of `test_XX.py` files, so it's mostly a matter of seeing in which it makes more sense, defaulting to [`test_model.py`](https://github.com/scipopt/PySCIPOpt/blob/6876af9db7fc3eb3d224c030ba8b53975fee2b20/tests/test_model.py). I think it makes sense to add it here. There's also the possibility of creating a new test file, if you think it is justified (it also needs to be prefixed by `test_`).

The test function needs to be prefixed by `test_`, and you can use some models we have stored in `helpers/utils.py`, in case you don't want to build a new one.

**Comment by DominikKamp** [comment]
Tests added but please verify that the console output is still as expected with and without `redirectOutput()`.

**Comment by DominikKamp** [comment]
Before doing anything else, it seems like the mac pipeline has to be fixed because it seems like the github runner is not able to compile the SCIPOptSuite before eternity ends (why not use the precompiled version like in the Windows-test?).

**Comment by Opt-Mucca** [comment]
Changes look good. I will test before merging.

**Comment by Opt-Mucca** [comment]
This does fix the issue on `writeProblem`. It also seems to help with #896

**Review by Opt-Mucca — APPROVED** [review]

**Comment by Opt-Mucca** [comment]
Let's wait until #933 is merged as then the pipelines can run faster

**Pull request merged**
