### PR TITLE
Fixed cutting stock example

### PR DESCRIPTION
**Pull request by Joao-Dionisio**
Fixed cutting_stock.py example that had the relax() and column() functions missing. Simplified the testing as well.

### CODE REVIEW

**Comment by Joao-Dionisio** [comment]
Sorry for removing the pull-request and adding it again. I'm new to this Git business, and I wanted to do it properly, with local branches and whatnot. I think it's better now.

**Comment by fserra** [comment]
Hey @Joao-Dionisio 

I have an issue with the example as it is. Although SCIP can, of course, be used as a black box solver, I believe that that's not SCIP's philosophy. The best example of that is the amount of work one needs to do in order to get the dual multipliers (although I guess one could just set up an LP problem and solve that instead of going through SCIP, see maybe `test_lp`

Anyway, it is my belief that the "SCIP way" of implementing the example, would be to write and add a pricer plugin (see `test_pricer`) and let all the column generation occur within the scip solving process. With the pricer, it should be trivial to obtain the dual multiplier, no need for strange workarounds or turning off presolve, propagation, etc.

The example would definitely be different from how it would be implemented in other solvers, but then again SCIP is a different type of solver and I guess it would be nice if the example would showcase this.

All that said, I am not involved in this repo that much anymore, so I guess the final word is @CGraczyk's.

**Comment by Joao-Dionisio** [comment]
Thanks for the reply, @fserra ! I started looking at this example due to issue [#281](https://github.com/scipopt/PySCIPOpt/issues/281), where the commenter asks for a way for his students to better understand column generation, I'm guessing because using the pricer is too opaque. But you're right, of course, I'll just pass the code to him, that's probably the way to go. Thanks for the input!

**Comment by fserra** [comment]
maybe the best is to use an LP for the pricing problem, because what #281 is asking for is very reasonable, and to be honest, I can't see how asking the students to disable presolve, add fixed variables to the bound, etc is any less obscure that just writing a pricing plugin.

**Comment by Joao-Dionisio** [comment]
Sorry for the delay. When I get the time I will incorporate your suggestions @fserra , thanks for the input!

**Pull request closed without merging**
