### PR TITLE
Change addConsNode to (also) accept ExprCons

### PR DESCRIPTION
**Pull request by CharJon**
Based on discussion in #416 
To keep the prototype simple a new addExprConsNode method is added.
Do you prefer having addConsNode accept ExprCons only or both (Constraint and ExprCons)?

### CODE REVIEW

**Comment by fserra** [comment]
thanks. I think it would make sense to factor out the code that creates the linear constraint since it also appears in `_addLinCons`

Regarding the name and if it should also be part of `addConsNode` I am unsure. I am pinging @mattmilten here.
So we have `addCons` and `addPyCons` for when the argument is an `ExprCons` or a `Constraint`, resp.
So for consistency, we could have `addConsNode` and `addPyConsNode`. 
But then we also have `addConsLocal` and we would need to do the same there.

An alternative would be to remove `addPyCons` and let `addCons` handle both cases.

**Comment by CharJon** [comment]
Personally I think the addPyCons naming is a bit confusing, as the `Constraint` objects are the ones actually having a pointer to a SCIPConstraint, while the ExprCons `addCons` expects as input don't. If you prefer having a single method for both cases I will restructure the code.

**Comment by mattmilten** [comment]
I prefer having a nice and easy-to-use method `addCons` that just accepts whatever you throw at it - be it `ExprCons` or `Constraint`.

**Comment by CharJon** [comment]
I made changes to addCons and addConsNode to avoid duplicate code. The current version of `addConsNode` works for `Constraint` and `ExprCons`. There a two TODOs in the code as I'm still unsure about how to handle the reference counting of SCIP. If you have any sources I could study to understand why and when `PY_SCIP_CALL(SCIPreleaseCons(self._scip, &scip_cons))` and `Py_INCREF(cons)` are necessary please tell me.

**Review by mattmilten — COMMENTED** [review]
Looks good to me. Just the CHANGELOG entry is missing.

**Comment by SanielDous** [comment]
Did this find its way into master branch already? Would be really nice

**Comment by zzy-opt** [comment]
I am implementing the branch and price where I need to add a linear constraint to the newly created node in branching rule. I am facing the exact same problem stated here.
The suggest solution definitely can solve my problem.  Howerever I don't see this updated version of addConsNode function exists. What goes wrong here? Isn't it successfully merged?

**Comment by zzy-opt** [comment]
@SanielDous Thank you. It seems this cannot be fixed in short term. Maybe I had better figure out how to use cython and change source code myself.

**Pull request merged**
