### PR TITLE
Number of readers method

### PR DESCRIPTION
**Pull request by jurgen-lentz**
The method ```getNReaders``` returns the number of available readers. I am also currently working on the ```Reader``` Plugin.

### CODE REVIEW

**Comment by mattmilten** [comment]
Thanks, @jurgen-lentz! Could you also add a short note to the CHANGELOG about this addition, please?

**Review by mattmilten — APPROVED** [review]
only the CHANGELOG entry is missing

**Comment by jurgen-lentz** [comment]
I have added an unreleased entry to the CHANGELOG.

**Comment by mattmilten** [comment]
Perfect, thanks!

**Pull request merged**
